profile: light
ceip_policy_disclosed: true # Installation fails if this is set to 'false'

buildservice:
  kp_default_repository: "dev.registry.tanzu.vmware.com/sliang/build-service"
  kp_default_repository_username: "xinstevenl@vmware.com"
  kp_default_repository_password: "$Dr34mJ0b$"
  tanzunet_username: "xinstevenl@vmware.com"
  tanzunet_password: "$Dr34mJ0b$"

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "dev.registry.tanzu.vmware.com"
    repository: "sliang/supply-chain"
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: "learningcenter.tap.poclab.me"

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "tap.poclab.me"
  app_config:
    app:
      baseUrl: http://tap-gui.tap.poclab.me
    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/bullblock/tap-poclab-me/master/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tap.poclab.me
      cors:
        origin: http://tap-gui.tap.poclab.me

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

contour:
  infrastructure_provider: aws
  envoy:
    service:
      aws:
        LBType: nlb

grype:
  namespace: "default" # (optional) Defaults to default namespace.
  targetImagePullSecret: "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"
